version: "3"

services:
  web:
    image: node
    ports:
      - 8090:3000
    volumes:
      - .:/app
    working_dir: /app
    restart: always
    depends_on:
      - package_installer
    command: npm start

  package_installer:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    command: npm install